import math

class CommandGenerator:
    FLANGE_DATA = {
        "DN50": {
            "outer_dia": 165,
            "thickness": 18,
            "hole_count": 4,
            "hole_dia": 18,
            "pcd": 125,
            "boss_dia": 102,
            "boss_height": 45
        },
        "DN100": {
            "outer_dia": 220,
            "thickness": 20,
            "hole_count": 8,
            "hole_dia": 18,
            "pcd": 180,
            "boss_dia": 158,
            "boss_height": 55
        }
    }

    @staticmethod
    def generate(schema: dict) -> list[str]:
        # Robustly intercept flange if generated by AI in any nested form
        flange_standard = None
        stype = schema.get("type")
        
        if stype == "flange":
            flange_standard = str(schema.get("standard"))
        elif "base" in schema and isinstance(schema["base"], dict) and schema["base"].get("type") == "flange":
            flange_standard = str(schema["base"].get("standard"))
        elif "features" in schema and isinstance(schema["features"], list):
            for f in schema["features"]:
                if isinstance(f, dict) and f.get("type") == "flange":
                    flange_standard = str(f.get("standard"))
                    break
        
        if flange_standard is not None:
            standard = flange_standard
            if standard not in CommandGenerator.FLANGE_DATA:
                return ["create plate length 100 width 100 thickness 10"]
            
            data = CommandGenerator.FLANGE_DATA[standard]
            commands = []
            commands.append(f"create plate length {data['outer_dia']} width {data['outer_dia']} thickness {data['thickness']}")
            commands.append(f"add boss radius {int(data['boss_dia'] / 2)} height {data['boss_height']}")
            
            hole_r = int(data['hole_dia'] / 2)
            pcd_r = data['pcd'] / 2
            
            for i in range(data['hole_count']):
                angle = (2 * math.pi * i) / data['hole_count']
                x = round(pcd_r * math.cos(angle), 2)
                y = round(pcd_r * math.sin(angle), 2)
                
                # Eliminate negative zero
                if x == 0: x = 0
                if y == 0: y = 0
                
                commands.append(f"add hole radius {hole_r} at {x:g} {y:g}")
                
            return commands
            
        if stype == "plate":
            return [f"create plate length 100 width 100 thickness {schema.get('thickness', 10)}"]
        elif stype == "fillet":
            return [f"add fillet {schema.get('radius', 5)}"]

        if "base" not in schema:
            raise ValueError("Schema must contain a 'base' object")
            
        base = schema["base"]
        if "type" not in base:
            raise ValueError("Base object must have a 'type'")
            
        commands = []
        
        # Parse base
        btype = base["type"]
        if btype == "box":
            l, w, h = base.get("length"), base.get("width"), base.get("height")
            if l is None or w is None or h is None:
                raise ValueError("Box requires length, width, and height")
            commands.append(f"create box length {l} width {w} height {h}")
        elif btype == "plate":
            l, w, t = base.get("length"), base.get("width"), base.get("thickness")
            if l is None or w is None or t is None:
                raise ValueError("Plate requires length, width, and thickness")
            commands.append(f"create plate length {l} width {w} thickness {t}")
        elif btype == "cylinder":
            r, h = base.get("radius"), base.get("height")
            if r is None or h is None:
                raise ValueError("Cylinder requires radius and height")
            commands.append(f"create cylinder radius {r} height {h}")
        elif btype == "sphere":
            r = base.get("radius")
            if r is None:
                raise ValueError("Sphere requires radius")
            commands.append(f"create sphere radius {r}")
        elif btype == "cone":
            r1, r2, h = base.get("radius1"), base.get("radius2"), base.get("height")
            if r1 is None or r2 is None or h is None:
                raise ValueError("Cone requires radius1, radius2, and height")
            commands.append(f"create cone radius1 {r1} radius2 {r2} height {h}")
        elif btype == "tube":
            out_r, in_r, h = base.get("outer"), base.get("inner"), base.get("height")
            if out_r is None or in_r is None or h is None:
                raise ValueError("Tube requires outer, inner, and height")
            commands.append(f"create tube outer {out_r} inner {in_r} height {h}")
        else:
            raise ValueError(f"Unsupported base type: {btype}")
            
        # Parse features
        features = schema.get("features", [])
        if not isinstance(features, list):
            raise ValueError("Features must be a list")
            
        for f in features:
            if "type" not in f:
                continue
            ftype = f["type"]
            
            if ftype == "hole":
                r = f.get("radius")
                if r is None:
                    raise ValueError("Hole requires radius")
                
                count = f.get("count", 1)
                pattern = f.get("pattern", "single")
                
                if count > 1 and pattern in ["corner", "linear"]:
                    commands.append(f"add {count} hole radius {r} {pattern}")
                else:
                    commands.append(f"add hole radius {r}")
                    
            elif ftype == "fillet":
                r = f.get("radius")
                if r is None:
                    raise ValueError("Fillet requires radius")
                commands.append(f"add fillet {r}")
                
            elif ftype == "chamfer":
                r = f.get("radius")
                if r is None:
                    raise ValueError("Chamfer requires radius")
                commands.append(f"add chamfer {r}")
                
            elif ftype == "slot":
                l, w = f.get("length"), f.get("width")
                if l is None or w is None:
                    raise ValueError("Slot requires length and width")
                commands.append(f"add slot length {l} width {w}")
                
            elif ftype == "boss":
                r, h = f.get("radius"), f.get("height")
                if r is None or h is None:
                    raise ValueError("Boss requires radius and height")
                commands.append(f"add boss radius {r} height {h}")
                
            elif ftype == "mirror":
                axis = f.get("axis")
                if not axis:
                    raise ValueError("Mirror requires axis")
                commands.append(f"mirror along {axis}")
                
            elif ftype == "scale":
                factor = f.get("factor")
                if factor is None:
                    raise ValueError("Scale requires factor")
                commands.append(f"scale {factor}")
                
            else:
                raise ValueError(f"Unsupported feature type: {ftype}")
                
        return commands
